import Foundation

/// The Swift library's built-in localization catalog.
///
/// Keeping this catalog in source makes the CLI self-contained: SwiftPM no
/// longer needs to ship a resource bundle beside the executable.
internal enum TMDLocalizationCatalog {
    static let values: [String: [String: String]] = [
        "en": [
            "report.title": "TMD Song Profile",
            "report.duration": "Duration",
            "report.measuresTotal": "measures total",
            "report.playbackBase": "Movable-do base",
            "report.keyAndTempo": "Key & Tempo",
            "report.analysisScope": "Analysis scope:     Inferred tonality from sounding note and chord evidence; playback context is reported separately",
            "report.structure": "Structure",
            "report.density": "Density",
            "report.tracksConcurrently": "tracks concurrently",
            "report.harmony": "Harmony",
            "report.tonalityDiagnosis": "Tonality diagnosis:",
            "report.mood": "Mood",
            "report.modulationJourney": "Modulation journey",
            "report.tonalCore": "Tonal core",
            "report.tonalMetrics": "Tonality metrics",
            "report.correlation": "correlation",
            "report.stability": "stability",
            "report.diatonicPurity": "diatonic purity",
            "report.candidateKeys": "Best-fit keys (K-S)",
            "report.circleOfFifths": "Circle of fifths trajectory",
            "report.sectionDetails": "Section tonality details",
            "report.nonDiatonic": "non-diatonic",
            "report.instrumentRanges": "Instrument Track Ranges:",
            "report.notes": "notes",
            "report.semitones": "semitones",
            "report.octaves": "octaves",
            "key.major": "Major",
            "key.minor": "Minor",
            "tonality.mode.ambiguous": "Ambiguous",
            "tonality.mode.modal": "Modal",
            "tonality.mode.insufficient": "Insufficient evidence",
            "tonality.modulation.none": "The song stays in one tonality (no inferred modulation)",
            "tonality.modulation.start": "Starts in {0} {1}",
            "tonality.modulation.step": "[{0}] to {1} ({2} semitones / {3} fifths)",
            "tonality.summary.stable": "{0} {1} ({2}, no inferred modulation)",
            "tonality.summary.modulating": "{0} {1} (inferred modulation through {2} transition(s))",
            "tonality.summary.clean": "clean major tonality",
            "tonality.summary.color": "contemporary major color",
            "tonality.summary.cleanMinor": "clean minor tonality",
            "tonality.summary.colorMinor": "contemporary minor color",
            "tonality.mood.cleanMajor": "Clean major tonality (bright, singable, and memorable)",
            "tonality.mood.contemporaryMajor": "Contemporary major tonality (with chord tones and secondary-dominant color)",
            "tonality.mood.cleanMinor": "Clean minor tonality (focused, lyrical, and without strong chromatic color)",
            "tonality.mood.contemporaryMinor": "Contemporary minor tonality (with chord tones and secondary-dominant color)",
            "tonality.mood.modal": "Modal or blues-influenced color (rich chromatic tension)",
            "tonality.mood.insufficient": "Insufficient musical evidence for a reliable tonality inference",
            "visualizer.circleOfFifths": "Circle of Fifths Trajectory",
            "visualizer.pitchClassDistribution": "12-Tone Pitch Class Distribution",
            "visualizer.timeline": "Timeline Keyscape Ribbon",
            "visualizer.htmlTitle": "TMD Tonality Report",
            "visualizer.htmlSong": "Song",
            "visualizer.htmlTempo": "Tempo",
            "visualizer.htmlKey": "Key",
            "visualizer.htmlDetailedReport": "Detailed Text Analysis",
            "visualizer.inferredTonality": "Inferred Tonality",
            "visualizer.confidence": "Confidence",
            "visualizer.diatonicEvidence": "Sounding diatonic ratio",
            "visualizer.ambiguous": "Ambiguous"
        ],
        "zh-Hant": [
            "report.title": "TMD Song Profile",
            "report.duration": "Duration",
            "report.measuresTotal": "measures total",
            "report.playbackBase": "首調基準",
            "report.keyAndTempo": "Key & Tempo",
            "report.analysisScope": "分析範圍：      由實際發聲的音符與和弦推測調性；播放脈絡另行呈現",
            "report.structure": "結構",
            "report.density": "編曲密度",
            "report.tracksConcurrently": "軌道同時演奏",
            "report.harmony": "和聲",
            "report.tonalityDiagnosis": "調性診斷：",
            "report.mood": "風格氣質",
            "report.modulationJourney": "轉調歷程",
            "report.tonalCore": "核心骨幹音",
            "report.tonalMetrics": "調性數值",
            "report.correlation": "相關度",
            "report.stability": "穩定度",
            "report.diatonicPurity": "自然音純度",
            "report.candidateKeys": "候選調性 (K-S)",
            "report.circleOfFifths": "五度圈歷程",
            "report.sectionDetails": "各段落調性細節",
            "report.nonDiatonic": "調外音",
            "report.instrumentRanges": "樂器軌道音域：",
            "report.notes": "個音符",
            "report.semitones": "個半音",
            "report.octaves": "個八度",
            "key.major": "大調",
            "key.minor": "小調",
            "tonality.mode.ambiguous": "調性不明確",
            "tonality.mode.modal": "調式",
            "tonality.mode.insufficient": "音樂資料不足",
            "tonality.modulation.none": "全曲維持單一推測調性（未偵測到可信轉調）",
            "tonality.modulation.start": "{0} {1}起奏",
            "tonality.modulation.step": "[{0}] 轉至 {1} ({2} 半音 / 五度圈 {3} 步)",
            "tonality.summary.stable": "{0} {1}（{2}，未偵測到可信轉調）",
            "tonality.summary.modulating": "{0} {1}（推測轉調經歷 {2} 次）",
            "tonality.summary.clean": "純淨自然大調",
            "tonality.summary.color": "流行色彩大調",
            "tonality.summary.cleanMinor": "純淨自然小調",
            "tonality.summary.colorMinor": "流行色彩小調",
            "tonality.mood.cleanMajor": "純淨自然大調（陽光明朗、易唱易記，無明顯調外色彩）",
            "tonality.mood.contemporaryMajor": "流行大調（略帶和弦色彩音與裝飾副屬和弦）",
            "tonality.mood.cleanMinor": "純淨自然小調（陰鬱抒情、旋律集中，無明顯調外色彩）",
            "tonality.mood.contemporaryMinor": "流行小調（略帶和弦色彩音與裝飾副屬和弦）",
            "tonality.mood.modal": "調式色彩／藍調前衛（調外音豐富，張力強烈）",
            "tonality.mood.insufficient": "音樂資料不足，暫無法可靠推測調性",
            "visualizer.circleOfFifths": "五度圈游移軌跡",
            "visualizer.pitchClassDistribution": "十二半音累積音高分佈",
            "visualizer.timeline": "時間線調性帶",
            "visualizer.htmlTitle": "TMD 調性報告",
            "visualizer.htmlSong": "歌曲",
            "visualizer.htmlTempo": "速度",
            "visualizer.htmlKey": "調性",
            "visualizer.htmlDetailedReport": "詳細文字分析",
            "visualizer.inferredTonality": "調性推論",
            "visualizer.confidence": "可信度",
            "visualizer.diatonicEvidence": "發聲音高的自然音比例",
            "visualizer.ambiguous": "調性不明確"
        ]
    ]
}
